name: Astronomer CI - Create preview Deployment

on:
  push:
    branches:
      - main

env:
  ## Set your API token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create preview Deployment
      uses: astronomer/deploy-action@v0.2
      with:
        action: create-deployment-preview
        deployment-id: clqnjfwie385204k8xc03jg28gd
